export type PortfolioLocale = "zh" | "en";

export const portfolioCopy = {
  zh: {
    htmlLang: "zh-CN",
    ownerAvatarAlt: "丁小山头像",
    keyLogoAlt: "祥云玉石钥匙品牌标识",
    keyLogoLabel: "查看祥云玉钥 3D 模型",
    productLabel: "公开投资日志",
    title: "百万美元之路",
    subtitle: "丁小山美股公开投资",
    journey: {
      alternateTitle: "The Million Dollar Journey",
      route: "$10,000 → $1,000,000",
      motto: "One Portfolio. One Journey.",
      routeStart: "起点",
      routeCurrent: "当前",
      routeTarget: "目标",
      weeklyPulse: "本周近况：仍在回本区，盯日终净值就好。",
      currentPortfolio: "当前组合",
      totalReturn: "累计收益",
      progress: "旅程进度",
      usdBasis: "以 10,000 美元为起点计算",
      cnyReference: "人民币参考",
      remainingToStart: (value: string) => `回本 · 还差 ${value}`,
      remainingToTarget: (value: string) => `距离 $1M 目标还差 ${value}`,
      milestones: "里程碑",
      milestonesNote: "达到日期以 IBKR 日终净值首次越过目标为准",
      milestone: (index: number) => `Milestone ${String(index).padStart(2, "0")}`,
      achieved: "已达成",
      next: "下一目标",
      locked: "尚未解锁",
      recordedSince: (days: number) => `已记录 ${days.toLocaleString("zh-CN")} 天`,
      noRecordedDate: "尚无可验证日期",
    },
    latestRefresh: "最新刷新",
    closeData: "收盘数据",
    baseCurrency: "显示币种",
    languageLabel: "语言",
    languageZh: "中文",
    languageEn: "English",
    sync: {
      dataChip: "数据",
      authorizeCta: "需授权自动同步→",
      initial: "需授权自动同步→",
      failed: "最近同步失败 · 已保留上次数据",
      automatic: "IBKR 日终自动同步",
      pending: "已授权 · 等待首次日终同步",
      waiting: "需授权自动同步→",
      fallback: "当前为最近验证快照",
    },
    fx: {
      label: "实时汇率",
      loading: "正在获取 USD/CNY",
      live: "实时",
      stale: "延迟",
      unavailable: "人民币换算暂不可用，当前显示美元",
      unavailableUnderCurrent: "汇率暂不可用",
      rate: (value: string) => `1 USD = ¥${value}`,
      quotedAt: (value: string) => `报价 ${value}`,
    },
    summaryAria: "账户摘要",
    metrics: {
      netAsset: "净资产（NLV）",
      cash: "现金",
      availableFunds: "可用资金",
      dailyPnl: "当日盈亏",
      leverage: "账户杠杆",
      ytdReturn: "年度收益",
      weekReturn: "近 7 个交易日",
      previousSnapshot: (value: string) => `较上一快照 ${value}`,
      cashShare: (value: string) => `占比 ${value}`,
      buyingPower: (value: string) => `买入力 ${value}`,
      currentPositions: (value: string) => `当前持仓 · TWR ${value}`,
      largestPosition: (symbol: string, value: string) => `最大仓位 ${symbol} ${value}`,
      noPositions: "当前无持仓",
    },
    sections: {
      allocation: "资产配置",
      allocationNote: "持仓市值 + 现金",
      netAsset: "净资产",
      totalPositionRatio: "总持仓比例",
      trend: "净值曲线",
      trendAria: "净值趋势区间",
      periodStart: "期初",
      latest: "最新",
      pnl: "交易与盈亏",
      pnlNote: "当前数据源提供已实现与未实现盈亏；逐笔成交记录尚未接入",
      pnlPeriodAria: "盈亏统计区间",
      category: "类别",
      realized: (period: string) => `已实现（${period}）`,
      unrealized: "当前未实现",
      total: "合计",
      realizedYtd: (value: string) => `年初至今已实现盈亏为 ${value}；短周期已实现盈亏会随 Flex 成交明细持续补齐。`,
      holdings: "当前持仓",
      holdingsNote: "按绝对市值从高到低排列",
      options: "期权持仓",
      optionsNote: "自动识别 OPT / FOP 合约",
      contracts: (count: number) => `${count} 个合约`,
      noOptions: "当前没有期权持仓",
      noOptionsNote: "未来出现期权仓位时，会自动展示方向、数量、成本、市值和浮动盈亏。",
      contact: "联系方式",
      contactNote: "中国、美国与社交账号",
    },
    allocationAria: "当前资产配置",
    table: {
      ticker: "标的",
      contract: "合约",
      assetType: "资产类型",
      quantity: "数量",
      currentPrice: "现价",
      averageCost: "平均成本",
      valueWeight: "市值 / 权重",
      dailyPnl: "今日盈亏",
      unrealizedPnl: "未实现盈亏",
      stock: "股票",
      option: "期权",
      phone: "电话",
      email: "邮箱",
      callSign: "呼号",
    },
    risks: {
      aria: "风险关注",
      concentration: "集中度",
      highConcentration: "单一标的风险偏高",
      controlledConcentration: "集中度处于可控区间",
      exposure: "行业暴露",
      healthcare: "医疗科技 100%",
      diversified: "多标的组合",
      healthcareNote: "缺少跨行业分散",
      diversifiedNote: "请结合行业分类复核",
      cashBuffer: "现金缓冲",
      lowCash: "账户几乎满仓",
      cashAvailable: "保留一定现金缓冲",
      lastSevenDays: "过去 7 个交易日",
      closeSnapshot: "按日终净值快照计算",
    },
    footer: {
      source: (source: string) => `数据来源：${source} · 人民币金额按页面所示当前汇率换算 · 同步失败时保留上次成功快照。`,
      schedule: "每天北京时间 07:30 执行，IBKR 报表未就绪时自动重试。",
    },
  },
  en: {
    htmlLang: "en",
    ownerAvatarAlt: "Ding Xiaoshan profile photo",
    keyLogoAlt: "Cloud jade key brand mark",
    keyLogoLabel: "View the cloud jade key in 3D",
    productLabel: "Public Investment Log",
    title: "The Million Dollar Journey",
    subtitle: "Ding Xiaoshan U.S. Public Equity Portfolio",
    journey: {
      alternateTitle: "百万美元之路",
      route: "$10,000 → $1,000,000",
      motto: "One Portfolio. One Journey.",
      routeStart: "START",
      routeCurrent: "CURRENT",
      routeTarget: "TARGET",
      weeklyPulse: "Still ~$7.3k below the $10k start.",
      currentPortfolio: "Current Portfolio",
      totalReturn: "Total Return",
      progress: "Journey Progress",
      usdBasis: "Measured from the $10,000 starting line",
      cnyReference: "CNY reference",
      remainingToStart: (value: string) => `Break-even · ${value} to go`,
      remainingToTarget: (value: string) => `${value} remaining to the $1M goal`,
      milestones: "Milestones",
      milestonesNote: "Achievement dates use the first recorded IBKR close above each target",
      milestone: (index: number) => `Milestone ${String(index).padStart(2, "0")}`,
      achieved: "Achieved",
      next: "Next target",
      locked: "Locked",
      recordedSince: (days: number) => `${days.toLocaleString("en-US")} recorded days`,
      noRecordedDate: "No verified date yet",
    },
    latestRefresh: "LAST REFRESH",
    closeData: "Market close data",
    baseCurrency: "Base currency",
    languageLabel: "Language",
    languageZh: "中文",
    languageEn: "English",
    sync: {
      dataChip: "Data",
      authorizeCta: "Authorize auto-sync →",
      initial: "Authorize auto-sync →",
      failed: "Latest sync failed · showing the last snapshot",
      automatic: "IBKR end-of-day automatic sync",
      pending: "Authorized · awaiting the first end-of-day sync",
      waiting: "Authorize auto-sync →",
      fallback: "Showing the latest verified snapshot",
    },
    fx: {
      label: "Live FX",
      loading: "Loading USD/CNY",
      live: "Live",
      stale: "Delayed",
      unavailable: "CNY conversion is unavailable; showing USD",
      unavailableUnderCurrent: "FX unavailable",
      rate: (value: string) => `1 USD = CNY ${value}`,
      quotedAt: (value: string) => `Quoted ${value}`,
    },
    summaryAria: "Account summary",
    metrics: {
      netAsset: "Net Liquidation Value",
      cash: "Cash",
      availableFunds: "Available Funds",
      dailyPnl: "Daily P&L",
      leverage: "Account Leverage",
      ytdReturn: "Year-to-Date Return",
      weekReturn: "Last 7 Trading Days",
      previousSnapshot: (value: string) => `${value} vs. previous snapshot`,
      cashShare: (value: string) => `${value} of NLV`,
      buyingPower: (value: string) => `Buying power ${value}`,
      currentPositions: (value: string) => `Open positions · TWR ${value}`,
      largestPosition: (symbol: string, value: string) => `Largest position ${symbol} ${value}`,
      noPositions: "No open positions",
    },
    sections: {
      allocation: "Asset Allocation",
      allocationNote: "Position value + cash",
      netAsset: "Net assets",
      totalPositionRatio: "Gross exposure",
      trend: "Net Asset Curve",
      trendAria: "Net asset chart period",
      periodStart: "Opening",
      latest: "Latest",
      pnl: "Transactions & P&L",
      pnlNote: "The current source provides realized and unrealized P&L; trade-level rows are not yet connected",
      pnlPeriodAria: "P&L reporting period",
      category: "Category",
      realized: (period: string) => `Realized (${period})`,
      unrealized: "Current Unrealized",
      total: "Total",
      realizedYtd: (value: string) => `Year-to-date realized P&L is ${value}. Shorter realized periods will be populated from Flex transaction details.`,
      holdings: "Current Holdings",
      holdingsNote: "Sorted by absolute market value",
      options: "Option Positions",
      optionsNote: "Automatically detects OPT / FOP contracts",
      contracts: (count: number) => `${count} contract${count === 1 ? "" : "s"}`,
      noOptions: "No option positions",
      noOptionsNote: "Future option positions will automatically show direction, quantity, cost, market value, and unrealized P&L.",
      contact: "Contact",
      contactNote: "China, United States, and social account",
    },
    allocationAria: "Current asset allocation",
    table: {
      ticker: "Ticker",
      contract: "Contract",
      assetType: "Type",
      quantity: "Qty",
      currentPrice: "Last",
      averageCost: "Avg Cost",
      valueWeight: "Value / Wt",
      dailyPnl: "Day P&L",
      unrealizedPnl: "Unreal.",
      stock: "Stock",
      option: "Option",
      phone: "Phone",
      email: "Email",
      callSign: "Call Sign",
    },
    risks: {
      aria: "Risk highlights",
      concentration: "Concentration",
      highConcentration: "Single-name concentration is elevated",
      controlledConcentration: "Concentration is within the monitoring range",
      exposure: "Sector Exposure",
      healthcare: "Health Tech 100%",
      diversified: "Multi-name portfolio",
      healthcareNote: "No cross-sector diversification",
      diversifiedNote: "Review against formal sector classifications",
      cashBuffer: "Cash Buffer",
      lowCash: "The account is nearly fully invested",
      cashAvailable: "A cash buffer is available",
      lastSevenDays: "Last 7 Trading Days",
      closeSnapshot: "Calculated from end-of-day NAV snapshots",
    },
    footer: {
      source: (source: string) => `Source: ${source} · Updated after each U.S. trading day · The latest successful snapshot is retained if synchronization fails.`,
      schedule: "Runs every day at 07:30 China Standard Time and retries when the IBKR report is not ready.",
    },
  },
} as const;
