"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { calculateJourneyMetrics } from "../journey";
import { estimatePortfolio, quoteState, snapshotState } from "./valuation";
import type { LiveDashboard } from "./types";
import { marketSession } from "./market";
import { AdditionalInsights, SessionHistory, SystemStatus } from "./Insights";
import "./command-center.css";

type Locale = "zh" | "en";
const money = (n: number | null | undefined) => n == null ? "—" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(n);
const pct = (n: number | null | undefined) => n == null ? "—" : `${n >= 0 ? "+" : ""}${(n * 100).toFixed(2)}%`;
function time(value: string | null | undefined, locale: Locale) {
  return value && Number.isFinite(Date.parse(value)) ? new Intl.DateTimeFormat(locale === "zh" ? "zh-CN" : "en-US", { timeZone: "America/New_York", month: "short", day: "numeric", hour: "2-digit", minute: "2-digit", second: "2-digit", hourCycle: "h23" }).format(new Date(value)) + " ET" : "—";
}

function AnimatedValue({ value, className = "" }: { value: number | null; className?: string }) {
  const prior = useRef(value);
  const [previous, setPrevious] = useState(value);
  const [changing, setChanging] = useState(false);
  useEffect(() => {
    if (prior.current === value) return;
    setPrevious(prior.current); prior.current = value; setChanging(true);
    const id = setTimeout(() => setChanging(false), 450);
    return () => clearTimeout(id);
  }, [value]);
  const formatted = money(value), before = money(previous);
  return <span className={`v2-number ${className}`} aria-label={formatted}>{[...formatted].map((char, i) => <span aria-hidden="true" key={`${i}-${char}`} className={changing && char !== before[i] ? `digit-change ${(value ?? 0) >= (previous ?? 0) ? "up" : "down"}` : ""}>{char}</span>)}</span>;
}

function Provenance({ children, source, observed, imported, note, locale }: { children: React.ReactNode; source: string; observed?: string; imported?: string; note: string; locale: Locale }) {
  return <details className="v2-provenance"><summary>{children}<span className="source-hint">↗</span></summary><div className="provenance-popover"><b>{locale === "zh" ? "数据来源" : "DATA PROVENANCE"}</b><p>{source}</p><dl><dt>{locale === "zh" ? "数据时点" : "Observed"}</dt><dd>{observed ?? "—"}</dd><dt>{locale === "zh" ? "接收时间" : "Received"}</dt><dd>{time(imported, locale)}</dd></dl><small>{note}</small></div></details>;
}

const periods = ["1D", "7D", "1M", "3M", "YTD", "ALL"] as const;
function Performance({ data, locale }: { data: LiveDashboard; locale: Locale }) {
  const [period, setPeriod] = useState<typeof periods[number]>("1M");
  const [hover, setHover] = useState<number | null>(null);
  const t = (zh: string, en: string) => locale === "zh" ? zh : en;
  const history = data.portfolio?.navHistory ?? [];
  const end = new Date(`${data.portfolio?.asOf ?? data.market.date}T00:00:00Z`);
  const cutoff = period === "ALL" ? "" : period === "YTD" ? `${end.getUTCFullYear()}-01-01` : new Date(end.getTime() - ({ "7D": 7, "1M": 30, "3M": 90 }[period as "7D"] ?? 0) * 86_400_000).toISOString().slice(0, 10);
  const points = period === "1D" ? data.intraday.map(p => ({ date: p.time, value: p.value })) : history.filter(p => p.date >= cutoff);
  const min = Math.min(...points.map(p => p.value)), max = Math.max(...points.map(p => p.value));
  const span = Math.max(max - min, max * .01, 1);
  const coords = points.map((p, i) => [42 + i / Math.max(points.length - 1, 1) * 678, 210 - (p.value - min) / span * 155]);
  const path = coords.map((p, i) => `${i ? "L" : "M"}${p[0]},${p[1]}`).join(" ");
  const selected = points[hover ?? points.length - 1];
  return <section className="v2-panel performance"><div className="panel-heading"><div><span className="eyebrow">01 / {t("表现", "PERFORMANCE")}</span><h2>{t("资金如何变化", "The shape of progress")}</h2></div><span className="subtle">{period === "1D" ? t("行情估算 · USD", "Market estimate · USD") : t("IBKR 日终 · USD", "IBKR end-of-day · USD")}</span></div>
    <div className="chart-readout"><strong>{money(selected?.value)}</strong><span>{selected ? period === "1D" ? time(selected.date, locale) : selected.date : t("尚无本日行情样本", "No observed intraday samples")}</span></div>
    {points.length > 1 ? <svg className="v2-chart" viewBox="0 0 760 250" role="img" aria-label={t("账户净值曲线", "Portfolio value chart")} onMouseLeave={() => setHover(null)}><defs><linearGradient id="v2-chart-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#00d084" stopOpacity=".18"/><stop offset="100%" stopColor="#00d084" stopOpacity="0"/></linearGradient></defs>{[45, 100, 155, 210].map(y => <line key={y} x1="40" x2="725" y1={y} y2={y} stroke="var(--v2-border)" strokeDasharray="2 5"/>)}<path d={`${path} L720,225 L42,225Z`} fill="url(#v2-chart-fill)"/><path d={path} fill="none" stroke="#00d084" strokeWidth="2" vectorEffect="non-scaling-stroke"/>{coords.map((p, i) => <rect key={i} x={p[0] - 678 / points.length / 2} y="0" width={678 / points.length + 2} height="240" fill="transparent" onMouseEnter={() => setHover(i)} />)}{coords.at(-1) && <circle className={period === "1D" && data.estimate.state === "ESTIMATED" && data.market.state === "OPEN" ? "chart-tip pulse" : "chart-tip"} cx={coords.at(-1)![0]} cy={coords.at(-1)![1]} r="4" fill="#00d084"/>}{hover !== null && coords[hover] && <circle cx={coords[hover][0]} cy={coords[hover][1]} r="5" fill="var(--v2-text)"/>}<text x="42" y="247" fill="var(--v2-muted)" fontSize="12">{points[0].date.slice(0, 10)}</text><text x="720" y="247" textAnchor="end" fill="var(--v2-muted)" fontSize="12">{points.at(-1)?.date.slice(0, 10)}</text></svg> : <div className="chart-empty"><span className="empty-axis"/><p>{t("等待真实行情形成曲线", "A real curve starts with real observations")}</p><small>{t("不回填模拟价格；已核验历史可从其他区间查看。", "No simulated prices. Verified history is available in the other ranges.")}</small></div>}
    <div className="period-tabs" role="group" aria-label={t("曲线区间", "Chart period")}>{periods.map(p => <button key={p} onClick={() => { setPeriod(p); setHover(null); }} aria-pressed={period === p}>{p}</button>)}</div>
  </section>;
}

export default function CommandCenter({ initial, locale }: { initial: LiveDashboard; locale: Locale }) {
  const [received, setData] = useState(initial);
  const [clock, setClock] = useState(initial.servedAt);
  useEffect(() => { const id = setInterval(() => setClock(new Date().toISOString()), 10_000); return () => clearInterval(id); }, []);
  const currentMarket = marketSession(new Date(clock));
  const data = { ...received, market: currentMarket, estimate: estimatePortfolio(received.portfolio, received.quotes, currentMarket, new Date(clock)) };
  const [offline, setOffline] = useState(false);
  const [theme, setTheme] = useState("night");
  const t = (zh: string, en: string) => locale === "zh" ? zh : en;
  useEffect(() => { document.documentElement.lang = locale === "zh" ? "zh-CN" : "en"; const update = () => setTheme(new Date().getHours() >= 7 && new Date().getHours() < 19 ? "day" : "night"); update(); const id = setInterval(update, 60_000); return () => clearInterval(id); }, [locale]);
  useEffect(() => {
    const controller = new AbortController(); let pending = false;
    const refresh = async () => { if (document.hidden || pending) return; pending = true; try { const response = await fetch("/api/v2/dashboard", { cache: "no-store", signal: controller.signal }); if (!response.ok) throw new Error("unavailable"); const next = await response.json() as LiveDashboard; if (!next.servedAt || !next.market) throw new Error("invalid"); setData(next); setOffline(false); } catch { if (!controller.signal.aborted) setOffline(true); } finally { pending = false; } };
    void refresh(); const interval = setInterval(refresh, 30_000); document.addEventListener("visibilitychange", refresh);
    return () => { controller.abort(); clearInterval(interval); document.removeEventListener("visibilitychange", refresh); };
  }, []);
  const p = data.portfolio;
  const journey = calculateJourneyMetrics(p?.netLiquidation ?? 0, p?.navHistory ?? [], p?.asOf ?? data.market.date);
  const now = new Date(clock);
  const current = data.sessions.find(s => s.date === data.market.date);
  const largest = [...(p?.positions ?? [])].sort((a, b) => Math.abs(b.marketValue) - Math.abs(a.marketValue))[0];
  const concentration = p && largest ? Math.abs(largest.marketValue) / p.netLiquidation : null;
  const hasEstimate = data.estimate.value !== null;
  const note = t("日终持仓快照，不是实时账户余额。点击其他金额也可查看来源。", "End-of-day holdings snapshot, not a live account balance. Inspect any financial value for its source.");
  return <div className="command-center" data-theme={theme} lang={locale === "zh" ? "zh-CN" : "en"}><div className="v2-shell">
    <header className="v2-header"><Link href={locale === "zh" ? "/" : "/en"} className="v2-brand"><span className="brand-glyph">OI</span><div><b>OPENINVEST<span> AI</span></b><small>PUBLIC PORTFOLIO / IBKR</small></div></Link><nav><a href="#now">NOW</a><a href="#positions">{t("持仓", "POSITIONS")}</a><a href="#journey">JOURNEY</a></nav><div className="v2-header-end"><span className={`market-state market-${data.market.state.toLowerCase()}`} title={data.market.source}>● {data.market.state === "OPEN" ? t("常规交易时段", "MARKET OPEN") : data.market.state === "CLOSED" ? t("市场休市", "MARKET CLOSED") : t("交易日历待更新", "MARKET UNKNOWN")}</span><Link href={locale === "zh" ? "/en" : "/"}>{locale === "zh" ? "EN ↗" : "中文 ↗"}</Link><span className="version-tag">v2.0</span></div></header>
    <div className="v2-owner"><img src="/ding-xiaoshan-avatar.png" width="40" height="40" alt={t("丁小山", "Ding Xiaoshan")}/><span>{t("丁小山美股公开投资", "Ding Xiaoshan’s public portfolio")}</span><span className="owner-separator"/><p>{t("一个公开、可验证、持续运行的真实投资实验。", "A public, verifiable investment journey.")}</p><Link href="/jade-key" aria-label={t("祥云玉钥", "Jade key")}><img className="v2-key" src="/cloud-jade-key-mark-v3.webp" alt="" width="120" height="42"/></Link></div>
    {offline && <div className="v2-alert" role="status">{t("连接暂时中断，以下保留上次数据，不代表实时更新。", "Connection interrupted. Retaining the last observation, not live data.")}</div>}
    <main><section id="now" className="v2-hero"><div className="hero-kicker"><span className="eyebrow">THE MILLION DOLLAR JOURNEY</span><span className="subtle">{data.market.date} / NEW YORK</span></div><div className="hero-grid"><div className="hero-primary"><h1>{t("百万美元之路", "One portfolio. One journey.")}</h1><span className="value-label">{hasEstimate ? t("行情估算净值", "ESTIMATED PORTFOLIO VALUE") : t("已核验日终净值", "VERIFIED END-OF-DAY NAV")}</span><Provenance locale={locale} source={hasEstimate ? "IBKR holdings × market quotes + cash" : p?.source ?? "Unavailable"} observed={hasEstimate ? data.estimate.quotedAt ?? undefined : p?.asOf} imported={p?.updatedAt} note={hasEstimate ? t("基于上次持仓估算；不含之后未同步的交易和资金变动。", "Estimated from last confirmed holdings; excludes subsequent unsynced trades and cash movements.") : note}><AnimatedValue value={hasEstimate ? data.estimate.value : p?.netLiquidation ?? null} className="hero-amount"/></Provenance><div className="hero-status"><span className={`state-badge state-${(hasEstimate ? data.estimate.state : snapshotState(p?.asOf ?? "", now)).toLowerCase().replaceAll(" ", "-")}`}>{hasEstimate ? data.estimate.state : "✓ IBKR VERIFIED"}</span><span>{data.snapshotOrigin === "archive" ? t("归档快照 · ", "Archived snapshot · ") : ""}{p?.asOf}</span></div><div className="daily-change"><span className={data.estimate.change !== null && data.estimate.change < 0 ? "down" : "up"}>{money(data.estimate.change)} <small>{pct(data.estimate.changePercent)}</small></span><span>{t("相对行情前收盘 · 同持仓估算", "vs quote previous close · same holdings")}</span></div></div><aside className="truth-panel"><div><span className="eyebrow">TRUTH LAYER</span><span className="verified-mark">✓</span></div><h2>{t("IBKR 已核验", "IBKR verified")}</h2><strong>{money(p?.netLiquidation)}</strong><dl><dt>{t("报表日期", "Statement date")}</dt><dd>{p?.asOf ?? "—"}</dd><dt>{t("导入时间", "Imported")}</dt><dd>{time(p?.updatedAt, locale)}</dd><dt>{t("行情覆盖", "Quote coverage")}</dt><dd>{Math.round(data.estimate.coverage * 100)}%</dd></dl><p>{hasEstimate ? t("行情估值与确认净值独立保留。", "Market estimates never replace this record.") : t("行情尚未就绪；实时估值暂不可用。", "Quotes are not ready. Live estimate unavailable.")}</p><span className="feed-line">● {data.feed.configured ? data.feed.status.toUpperCase() : t("行情待连接", "FEED NOT CONNECTED")}</span></aside></div>
      <div className="v2-journey-bar"><div><span>START</span><b>$1,000</b></div><div className="journey-line" role="progressbar" aria-label={t("已核验净值目标进度", "Verified NAV journey progress")} aria-valuemin={0} aria-valuemax={100} aria-valuenow={journey.progress * 100}><span style={{ width: `${journey.progress * 100}%` }}/><i style={{ left: `${journey.progress * 100}%` }}/></div><div><span>TARGET</span><b>$1,000,000</b></div></div><div className="journey-foot"><span>{t("已核验进度", "VERIFIED PROGRESS")} <b>{(journey.progress * 100).toFixed(3)}%</b></span><span>{t("相对 $1K 起点增长", "GROWTH VS $1K BASELINE")} <b>{pct(journey.totalReturn)}</b></span><span>{t("不等同于剔除出入金的投资收益", "Not cash-flow-adjusted investment return")}</span></div>
    </section>
    <SystemStatus data={data} locale={locale} now={now} offline={offline}/>
    <div className="v2-live-grid"><Performance data={data} locale={locale}/><section className="v2-panel activity"><div className="panel-heading"><div><span className="eyebrow">02 / {t("事件", "ACTIVITY")}</span><h2>{t("此刻发生什么", "What changed")}</h2></div><span className="subtle">{data.activity.length} {t("条记录", "EVENTS")}</span></div><div className="activity-list" aria-live="polite" aria-relevant="additions">{data.activity.length ? data.activity.slice(0, 8).map(event => <article className="activity-event" key={event.id}><time>{time(event.occurredAt, locale)}</time><div><span className="event-icon">{event.kind === "verified" ? "✓" : "↗"}</span><b>{event.symbol ?? event.kind.toUpperCase()}</b>{event.value !== null && <strong>{money(event.value)}</strong>}</div><p>{event.detail}</p></article>) : <div className="activity-empty"><span>◎</span><h3>{t("真实变化，逐一记录", "Real changes. A lasting record.")}</h3><p>{t("行情连接后，报价变化、估值更新和 Session 事件会出现在这里。没有模拟活动。", "Observed quote changes, valuations and session events will appear here when the feed connects. No simulated activity.")}</p></div>}</div><div className="panel-bottom">{t("最新事件置顶 · 持久化记录", "Newest first · persistent observations")}</div></section></div>
    <section id="positions" className="v2-panel positions"><div className="panel-heading"><div><span className="eyebrow">03 / {t("持仓", "POSITIONS")}</span><h2>{t("钱在哪里", "What I own")}</h2></div><span className="subtle">{p?.positions.length ?? 0} {t("个持仓", "POSITIONS")} · USD</span></div><div className="v2-table-scroll"><table><thead><tr>{[t("企业 / 资产", "COMPANY / ASSET"), t("数量", "QTY"), t("价格 / 状态", "PRICE / STATE"), t("持仓市值", "MARKET VALUE"), t("浮动盈亏", "UNREALIZED P/L"), t("权重", "WEIGHT")].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{p?.positions.map(position => { const q = data.quotes.find(q => q.symbol === position.symbol); const state = quoteState(q, now, data.market); const value = q ? position.quantity * q.price : position.marketValue; return <tr key={position.contractKey}><td><div className="company"><img src={`/company-logos/${position.symbol.toLowerCase()}.png`} alt="" width="34" height="34" onError={e => { e.currentTarget.style.display = "none"; }}/><div><b>{position.symbol}</b><small>{position.name}</small></div></div></td><td>{position.quantity}</td><td><Provenance locale={locale} source={q?.source ?? p.source} observed={q?.quotedAt ?? p.asOf} imported={q?.receivedAt ?? p.updatedAt} note={q ? t("市场报价，用于估算。", "Market quote for estimation.") : note}><AnimatedValue value={q?.price ?? position.price}/></Provenance><small className="price-state">{q ? state : "IBKR EOD"}</small></td><td>{money(value)}<small className="price-state">{q ? "ESTIMATED" : "VERIFIED"}</small></td><td className={position.unrealizedPnl < 0 ? "down" : "up"}>{money(position.unrealizedPnl)}<small className="price-state">IBKR · {p.asOf}</small></td><td>{(position.marketValue / p.netLiquidation * 100).toFixed(1)}%<span className="weight-track"><i style={{ width: `${Math.min(100, Math.abs(position.marketValue / p.netLiquidation * 100))}%` }}/></span></td></tr>; })}</tbody></table></div><div className="panel-bottom">{t("权重和浮动盈亏使用已核验日终口径。盘中估值不代表下单或实时券商余额。", "Weights and unrealized P/L use verified EOD records. Estimates are not trading instructions or live broker balances.")}</div></section>
    <AdditionalInsights data={data} locale={locale}/>
    <div className="v2-lower-grid"><section className="v2-panel"><div className="panel-heading"><div><span className="eyebrow">PORTFOLIO PULSE</span><h2>{t("组合脉搏", "At a glance")}</h2></div></div><dl className="pulse-list"><dt>{t("最大持仓", "Largest holding")}</dt><dd>{largest?.symbol ?? "—"} <b>{concentration === null ? "—" : `${(concentration * 100).toFixed(1)}%`}</b></dd><dt>{t("集中度", "Concentration")}</dt><dd className={concentration !== null && concentration > .5 ? "warning" : ""}>{concentration === null ? "—" : concentration > .5 ? t("高", "HIGH") : t("适中", "MODERATE")}</dd><dt>{t("现金占比", "Cash weight")}</dt><dd>{p ? `${(p.totalCash / p.netLiquidation * 100).toFixed(3)}%` : "—"}</dd><dt>{t("组合 Beta", "Portfolio beta")}</dt><dd>— <small>{t("未计算", "Not calculated")}</small></dd><dt>{t("今日已观测区间", "Observed range")}</dt><dd>{current ? `${money(current.low)} – ${money(current.high)}` : "—"}</dd></dl></section><section className="v2-panel"><div className="panel-heading"><div><span className="eyebrow">DAILY SESSION</span><h2>{current?.date ?? data.market.date}</h2></div><span className="state-badge">{current?.status ?? t("等待采样", "AWAITING DATA")}</span></div><div className="session-grid">{[[t("首个估值", "FIRST OBSERVATION"), current?.openingNav], [t("当前估值", "CURRENT"), current?.current], [t("最高", "HIGH"), current?.high], [t("最低", "LOW"), current?.low]].map(([label, value]) => <div key={String(label)}><span>{label}</span><b>{money(value as number | undefined)}</b></div>)}</div><div className="panel-bottom">{t("仅封存实际观测到的估值，非券商日终结算。", "Sealed observations are market estimates, not broker settlement.")}</div></section></div>
    <SessionHistory data={data} locale={locale}/>
    <section id="journey" className="v2-narrative"><div><span className="eyebrow">THE LONG VIEW</span><h2>{t("时间，是这场旅程的另一条轴。", "A long journey. An honest record.")}</h2><p>{t("从第一条已核验记录开始。每一个里程碑，都有据可查。", "From the first verified observation. Every milestone has a traceable date.")}</p></div><div className="v2-milestones">{journey.milestones.map((m, i) => <article key={m.value} className={`milestone-${m.status}`}><span>{String(i + 1).padStart(2, "0")} {m.status === "achieved" ? "✓" : m.status === "next" ? "↗" : "○"}</span><b>{money(m.value).replace(".00", "")}</b><small>{m.reachedAt ?? (m.status === "next" ? t("下一站", "NEXT") : t("未到达", "AHEAD"))}</small>{m.daysFromJourneyStart !== null && <small>DAY {m.daysFromJourneyStart}</small>}</article>)}</div></section>
    <section className="v2-panel history"><div className="panel-heading"><div><span className="eyebrow">THE RECORD</span><h2>{t("可追溯的历史", "Nothing without a source")}</h2></div></div><div className="history-columns"><div><h3>{t("已核验净值", "Verified history")}</h3>{p?.navHistory.slice(-5).reverse().map(point => <p key={point.date}><time>{point.date}</time><b>{money(point.value)}</b></p>)}</div><div><h3>{t("成交记录", "Trades")}</h3>{data.trades.length ? data.trades.slice(0, 5).map(trade => <p key={trade.tradeId}><span>{trade.tradeDate} · {trade.symbol} {trade.side}</span><b>{trade.quantity} × {money(trade.price)}</b></p>) : <p className="subtle">{t("尚未接入可核验成交，不以零成交代替缺失数据。", "No verified trade records connected. Missing data does not mean zero trades.")}</p>}</div><div><h3>{t("方法与备注", "Method & notes")}</h3><p>{t("实时估值 = 已确认持仓 × 最新报价 + 已确认现金。持仓变化、出入金、费用和公司行动可能造成偏差。", "Estimate = confirmed positions × latest quotes + confirmed cash. Trades, transfers, fees and corporate actions can create differences.")}</p><p>{t("所有时间标注时区；报价、导入与报表日期分别展示。", "Quote time, import time and statement date are kept separate.")}</p></div></div></section>
    </main><footer className="v2-footer"><div><b>OPENINVEST AI</b><p>{t("公开记录，不构成投资建议。只读观察，不提供交易功能。", "A public record, not investment advice. Read-only. No trading functionality.")}</p></div><div className="v2-contacts"><a href="https://x.com/languagemodelAI" target="_blank" rel="noreferrer">X / @languagemodelAI ↗</a><a href="mailto:0288882@gmail.com">0288882@gmail.com</a><a href="tel:+8619951677665">CN +86 19951677665</a><a href="tel:+19809990101">US +1 980 999 0101</a><a href="mailto:people@china.com">people@china.com</a><span>BD4WUC <img src="/bd4wuc-amateur-radio-logo.webp" width="26" height="26" alt="BD4WUC Amateur Radio"/></span></div></footer>
  </div></div>;
}
